django-tablebooking-master/django-tablebooking-master/About/urls.py
from django.urls import path
from . import views

app_name='about'


urlpatterns=[
    path('about/',views.AboutPageView.as_view(),name='about'),
    #path('about/',views.AboutPage,name='about') """Function based Views"
]

django-tablebooking-master/django-tablebooking-master/Booking/urls.py
from django.urls import path
from . import views

app_name='Booking'

urlpatterns=[
    path('event/',views.EventBooking,name='event'),
    path('table/',views.TableBooking,name='table'),
    path('pay/',views.payment,name='pay'),
]

django-tablebooking-master/django-tablebooking-master/Contact/urls.py
from django.urls import path
from . import views

app_name ='Contact'

urlpatterns=[
    path('contact/',views.ContactPage,name='contact')
]

django-tablebooking-master/django-tablebooking-master/Home/urls.py
from django.urls import path
from . import views

app_name='Home'

urlpatterns=[
    path('',views.IndexPageView.as_view(),name='index'),
    #path('',views.IndexPage,name='index'),
]

django-tablebooking-master/django-tablebooking-master/Menu/urls.py
from django.urls import path
from . import views

app_name='Menu'

urlpatterns =[
    path('menu/',views.MenuPageView.as_view(),name='menu'),
    #path('menu/',views.MenuPage,name='menu'), """Function based Views"""
]

django-tablebooking-master/django-tablebooking-master/TableBooking/TableBooking/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls')),
    path('booking/',include('Booking.urls',namespace='booking')),
    path('',include('Menu.urls')),
    path('',include('Contact.urls')),
    path('',include('About.urls')),
path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
path('accounts/',include('account.urls')),
]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-tablebooking-master/django-tablebooking-master/TableBooking/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls')),
    path('booking/',include('Booking.urls',namespace='booking')),
    path('',include('Menu.urls')),
    path('',include('Contact.urls')),
    path('',include('About.urls')),
path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
path('accounts/',include('account.urls')),

]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-tablebooking-master/django-tablebooking-master/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django-tablebooking-master/django-tablebooking-master/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'img/express-favicon.png' %}" type="image/x-icon" />
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>
          {% block title%}

          {%endblock title%}
        </title>

        <!-- Icon css link -->
        <link href="{% static 'vendors/material-icon/css/materialdesignicons.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/linears-icon/style.css' %}" rel="stylesheet">
        <!-- Bootstrap -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Rev slider css -->
        <link href="{% static 'vendors/revolution/css/settings.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/revolution/css/layers.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/revolution/css/navigation.css' %}" rel="stylesheet">

        <!-- Extra plugin css -->
        <link href="{% static 'vendors/bootstrap-selector/bootstrap-select.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/bootatrap-date-time/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/owl-carousel/assets/owl.carousel.css' %}" rel="stylesheet">

        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <div id="preloader">
            <div class="loader absolute-center">
                <div class="loader__box"><b class="top"></b></div>
                <div class="loader__box"><b class="top"></b></div>
                <div class="loader__box"><b class="top"></b></div>
            </div>
        </div>

        <!--================ Frist hader Area =================-->
        <div class="first_header">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="header_contact_details">
                            <a href="#"><i class="fa fa-phone"></i>+91 7331129888</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="event_btn_inner">
                            <a class="event_btn" href="{% url 'Booking:table' %}"><i class="fa fa-table" aria-hidden="true"></i>Book a Table</a>
                            <a class="event_btn" href="{% url 'Booking:event' %}"><i class="fa fa-calendar" aria-hidden="true"></i>restaurant</a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="header_social">
                            <ul>
                                <li><a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="https://www.instagram.com/?hl=en"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="https://www.linkedin.com/feed/"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--================End Footer Area =================-->

        <!--================End Footer Area =================-->
        <header class="main_menu_area">
            <nav class="navbar navbar-default">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"><img src="{% static 'img/logo-3m.png' %}" alt=""></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="{% url 'Home:index' %}">Home</a></li>
                            <li><a href="{% url 'about:about' %}">About Us</a></li>
                            <li><a href="{% url 'Menu:menu' %}">Menu</a></li>


                            <li class="dropdown submenu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Booking <i class="fa fa-angle-down" aria-hidden="true"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{%url 'Booking:event' %}">Event</a></li>
                                    <li><a href="{% url 'Booking:table' %}">Table</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'Contact:contact'%}">Contact US</a></li>

                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        </header>
        <!--================End Footer Area =================-->
{% block content%}


{%endblock content%}

        <footer class="footer_area">
            <div class="footer_widget_area">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <aside class="f_widget about_widget">
                                <div class="f_w_title">
                                    <h4>ABOUT Book MY Table</h4>
                                </div>
                                <p>This is a platform that is meant for reserving a table at any restaurant according to the customer choices. </p>
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                </ul>
                            </aside>
                        </div>
                        <div class="col-md-6">
                            <aside class="f_widget contact_widget">
                                <div class="f_w_title">
                                    <h4>CONTACT US</h4>
                                </div>
                                <p>Have questions, comments or just want to say hello:</p>
                                <ul>
                                    <li><a href="#"><i class="fa fa-envelope"></i>info@mytable.com.au</a></li>
                                    <li><a href="#"><i class="fa fa-phone"></i>+61 (0)451 956 182</a></li>
                                    <li><a href="#"><i class="fa fa-map-marker"></i>393 Liverpool Rd,<br /> Ashfield, NSW 2131</a></li>
                                </ul>
                            </aside>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copy_right_area">
                <div class="container">
                    <div class="pull-left">
                        <h5><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p></h5>
                    </div>
                    <div class="pull-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="{% url 'Home:index' %}">Home</a></li>
                            <li><a href="{% url 'about:about' %}">About Us</a></li>
                            <li><a href="{% url 'Menu:menu' %}">Menu</a></li>
                            <li><a href="{% url 'Booking:table' %}">Table Booking</a></li>
                            <li><a href="{%url 'Booking:event' %}">Event Booking</a></li>
                            <li><a href="{% url 'Contact:contact' %}">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!--================End Recent Blog Area =================-->



        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- Rev slider js -->
        <script src="{% static 'vendors/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
        <script src="{% static 'vendors/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
        <script src="{% static 'vendors/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
        <script src="{% static 'vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
        <script src="{% static 'vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
        <script src="{% static 'vendors/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
        <script src="{% static 'vendors/revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
        <!-- Extra plugin js -->
        <script src="{% static 'vendors/bootstrap-selector/bootstrap-select.js' %}"></script>
        <script src="{% static 'vendors/bootatrap-date-time/bootstrap-datetimepicker.min.js' %}"></script>
        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/countdown/jquery.countdown.js' %}"></script>
        <script src="{% static 'vendors/js-calender/zabuto_calendar.min.js' %}"></script>
        <!--gmaps Js-->
<!--        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>-->
<!--        <script src="js/gmaps.min.js"></script>-->


<!--        <script src="js/video_player.js"></script>-->
        <script src="{% static 'js/theme.js' %}"></script>
    </body>
</html>

django-tablebooking-master/django-tablebooking-master/templates/signup.html
{% block title %}  {% endblock %}
{% block content %}
<style>
     body{background-color:beige;}
</style>
<body>
 <h2>Sign up</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Sign up</button>
    </form>
{% endblock %}
</body>